[workspace]
members = [
    "crates/it-lilo",
    "crates/to-bytes",
    "crates/it-types",
    "crates/it-memory-traits",
    "wasmer-it",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
