[package]
name = "it-lilo"
version = "0.1.0"
authors = ["Fluence Labs"]
description = "Defines some helper utils for lifting/lowering IT"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "it_lilo"
path = "src/lib.rs"

[dependencies]
fluence-it-types = { path = "../it-types/", version = "0.3.0" }
it-utils = {path="../utils"}

paste = "1.0.5"
thiserror = "1.0.24"
log = "0.4.14"
