[package]
name = "wasmer-interface-types-fl"
version = "0.17.20"
description = "WebAssembly Interface Types library for Wasmer"
license = "MIT"
authors = ["The Wasmer Engineering Team <engineering@wasmer.io>"]
repository = "https://github.com/wasmerio/wasmer"
edition = "2018"

[dependencies]
fluence-it-types = { path = "../crates/it-types", version = "0.1.0", features = ["impls"] }

nom = "5.1"
wast = "8.0"

# `serde` is useful only to simplify the users' life. It is not
# required by WIT itself, is is used to cross the boundary between the
# host and WIT more easily, but it is not used inside Wasm.
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
serde_json = "1.0"
safe-transmute = "0.11.0"
log = "0.4.11"

[features]
default = ["serde"]
