name: Build

on: [pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: ubuntu-latest
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile the library
        run: cargo build --release

      # tests always fail, need refactoring
      # - name: Run all the tests
      #   run: cargo test --release
