name: "interface-types"

on:
  pull_request:

jobs:
  build:
    name: "Build"

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile the library
        run: cargo build --release

      # tests always fail, need refactoring
      # - name: Run all the tests
      #   run: cargo test --release
